In [1]:
# List cannot be manipulated directly in the way we want it
l= [2,3,4]
print(l)

[2, 3, 4]


In [2]:
import numpy as np

In [3]:
npa = np.array([2,3,4])
print(npa)

[2 3 4]


In [35]:
npa**2
aa=np.linspace(10,15,num=5)
print(aa)

[10.   11.25 12.5  13.75 15.  ]


In [5]:
# Manipulating with list is a tedious task
# declaring lists 
list1 = list(range(500000))  
# declaring numpy arrays 
array1 = np.arange(500000)

In [6]:
import time
initialTime = time.time() 
resultantList = [(a**2) for a in list1] #list comprehension
# calculating execution time 
print(time.time() - initialTime) 

0.13563942909240723


In [7]:
import time 
initialTime = time.time() 
resultantArray = array1 **2 
# calculating execution time  
print(time.time() - initialTime)

0.003026723861694336


In [8]:
#Arrays

#Import Numpy module
import numpy as np

# 1D Array
print("This is how a 1D array looks like.")
one = np.array([[1,2,3]])
print(one)
print(one.ndim)
print(type(one))
print(one.shape)
print(one.strides) #strides are the number of bytes that should be skipped in memory to go to the next element
print(one.data) #Python buffer object pointing to the start of the array’s data.

This is how a 1D array looks like.
[[1 2 3]]
2
<class 'numpy.ndarray'>
(1, 3)
(12, 4)


In [9]:
# 2D Array
print("This is how a 2D array looks like.")
print("\n")
two = np.array([[1,2,3],[4,5,6]])
print(two)
print(two.ndim)
print(type(two))
print(two.shape)
print(two.strides)

This is how a 2D array looks like.


[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
(2, 3)
(12, 4)


In [10]:
# 3D Array
print("This is how a 3D array looks like.")
print("\n")
three = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three)

This is how a 3D array looks like.


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
three[0,:,:]
three[1,:,:]
three[:,0,:]
three[:,1,:]
three[:,:,0]
three[:,:,1]

array([[2, 4],
       [6, 8]])

In [12]:
print(three.ndim)
# print(type(three))
print(three.shape)
print(three.strides)

3
(2, 2, 2)
(16, 8, 4)


In [13]:
#Creating array from a list

#Consider the list of heights of baseball players
height_inches = [61,65,63,69,70,73,68,64,63,62]

#Converting this list into numpy array
height_np_inches = np.array(height_inches)
print(height_np_inches)
# print(type(height_np_inches))
print(height_np_inches.ndim)

#Converting this array of height to cm
height_np_cm = height_np_inches * 2.54
print(height_np_cm)

[61 65 63 69 70 73 68 64 63 62]
1
[154.94 165.1  160.02 175.26 177.8  185.42 172.72 162.56 160.02 157.48]


In [14]:
#Weight of players in pounds
weight_pounds = [100,200,160,180,140,155,165,172,180,200]
#convert into numpy array
weight_np_pounds = np.array(weight_pounds)
weight_np_kgs = weight_np_pounds * 0.45
print(weight_np_kgs)
height_np_m = height_np_cm / 100
print(height_np_m)
#BMI(Weight(kg)/(height(m)^2))
# Underweight = <18.5
# Normal weight = 18.5–24.9
# Overweight = 25–29.9
# Obesity = BMI of 30 or greater
bmi = weight_np_kgs / (height_np_m ** 2)
print(bmi)

[45.   90.   72.   81.   63.   69.75 74.25 77.4  81.   90.  ]
[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]
[18.74499852 33.01781751 28.11797007 26.37056314 19.92861129 20.28761798
 24.889215   29.28960936 31.63271633 36.29039516]


In [15]:
#Finding out players with different BMI category
# c = (bmi>18.5) & (bmi<25)
# print(c)
# print(bmi[bmi>30])

In [16]:
#Subsetting a list
x = [4 , 9 , 6, 3, 1]
x[1]

9

In [17]:
#Subsetting arrays
y = np.array(x)
y[1]

9

In [18]:
#Boolean method for subsetting
high = y > 5
# y[high]

In [19]:
#Slicing the array
print(y[2:4])

[6 3]


In [20]:
#Making a 2D array from lists
baseball_total = [weight_np_kgs, height_np_m]
baseball_total_np = np.array(baseball_total)
print(baseball_total_np)
print(baseball_total_np.ndim)
print(baseball_total_np.shape)

[[45.     90.     72.     81.     63.     69.75   74.25   77.4    81.
  90.    ]
 [ 1.5494  1.651   1.6002  1.7526  1.778   1.8542  1.7272  1.6256  1.6002
   1.5748]]
2
(2, 10)


In [21]:
#Looking at the players data at index 2
print(baseball_total_np[0][2],baseball_total_np[1][2])

72.0 1.6002


In [22]:
baseball_total_np[:,2]

array([72.    ,  1.6002])

In [23]:
#Looking at all the players heights
print(baseball_total_np[1])

[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]


In [24]:
#Looking at all the players heights by another approach
print(baseball_total_np[1,:])

[1.5494 1.651  1.6002 1.7526 1.778  1.8542 1.7272 1.6256 1.6002 1.5748]


In [42]:
#Arithmatics with arrays
a = np.array([[0,1, 2], [3, 4,5]])
b = a.sum(axis=1)
print(b)

[ 3 12]


In [26]:
#Transpose
import numpy as np
a = np.array([[2,3,4]])
print(a)
print(a.shape)
# print("\n")
a_t = a.T
print(a_t)
print(a_t.shape)

[[2 3 4]]
(1, 3)
[[2]
 [3]
 [4]]
(3, 1)


In [27]:
#Swap axes
import numpy as np
a = np.array([[2,3,4]])
print(a)
print(a.shape)
a = np.swapaxes(a,1,0)
print(a)
print(a.shape)

[[2 3 4]]
(1, 3)
[[2]
 [3]
 [4]]
(3, 1)


In [28]:
#Universal functions
arr = np.arange(5)
print(arr)
# print("\n")
# Unary functions
print(np.sqrt(arr)) #Square root
print(np.exp(arr)) # Exponential

[0 1 2 3 4]
[0.         1.         1.41421356 1.73205081 2.        ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


In [29]:
#File Input and Output with Arrays
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
#Saving the array into file
np.save('xyz.npy', arr)

In [31]:

#Lcoading the file 
al = np.load('xyz.npy')

In [39]:
foo=(3,4,5)
print(type(foo))

<class 'tuple'>


In [33]:
#Ravel function for flattening of data
arr = np.arange(15).reshape((5, 3))
print("Before changing the ravelled array looking at original array")
print(arr)
print("\n")
rav1 = arr.ravel() #arr will change by changing of rav1
print(rav1)
print("\n")
rav1[0] = 1000
print(rav1)
print("\n")
print("After changing the ravelled array looking at original array")
print(arr)

Before changing the ravelled array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]


After changing the ravelled array looking at original array
[[1000    1    2]
 [   3    4    5]
 [   6    7    8]
 [   9   10   11]
 [  12   13   14]]


In [34]:
#Flatten function for flattening of data
arr = np.arange(15).reshape((5, 3))
print("Before changing the flattened array looking at original array")
print(arr)
flat1 = arr.flatten() #arr will not change by changing of flat1
print(flat1)
flat1[0] = 1000
print(flat1)
print("After changing the flattened array looking at original array")
print(arr)

Before changing the flattened array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14]
After changing the flattened array looking at original array
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
